# CCDC26 Wazuh Certificate Generator
#
# Generate SSL certificates for Wazuh components
#
# Usage:
#   docker compose -f generate-certs.yml run --rm generator
#
# This creates certificates in ./config/wazuh_indexer_ssl_certs/

version: '3.8'

services:
  generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    container_name: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs:/certificates/
      - ./config/certs.yml:/config/certs.yml:ro
